### ISSUE TITLE
error when attach files

### ISSUE THREAD

**Issue by vhchung** [andris9/nodemailer-wellknown#11]
When I attach files to email, all files will be send as  '.bin' with zero byte of content and cannot be read. Sorry for my poor english.

**Comment by andris9** [comment]
Could you provide an example script that I could run and verify the issue?

**Comment by vhchung** [comment]
I just run example code on [this site](http://adilapapaya.com/docs/nodemailer/#attachmentfields)

**Comment by andris9** [comment]
These docs are outdated and do not work with the current version of Nodemailer. If you still want to use it, then install Nodemailer version 0.7.1 which is the latest version that still supports the old specification.

    npm install nodemailer@0.7.1

**Comment by vhchung** [comment]
thank you :)
