### ISSUE TITLE
Trying to use Postmark

### ISSUE THREAD

**Issue by custa1200** [andris9/nodemailer-wellknown#14]
Hi I have the following:
```
var transporter = nodemailer.createTransport({
    service: 'postmark',
    auth: {
        user: 'myusername',
        pass: 'mypassword'
    },
    headers: {"X-Postmark-Server-Token": "mytoken"}
});
```

Where I have double checked the username is what I set up my account with at Postmark.The username is NOT an email address. I have just put dummy text in here for the purpose of the example structure. I have double checked the password and I have double checked the server token and they are all correctly copy pasted, but I get the following error showing in my Node console.

```
{ [Error: Invalid login]
  code: 'EAUTH',
  response: '535 5.7.8 Error: authentication failed: ',
  responseCode: 535 }
```

Maybe for each of the services in well known it would help to have some more descriptions about how to set up each service, i.e. having to add the headers for Postmark.

**Comment by andris9** [comment]
The specified header is for HTTP based Postmark API but this module is for SMTP. You need to provide valid credentials for Postmark SMTP and you can remove the headers field as it doesn't do anything (there are no headers in SMTP)
